### PR TITLE
added some style to the color selecting website

### PR DESCRIPTION
**Pull request by ejwyman64**
I made the appearance more centered and applied a black and white theme to the elements to really make the colors pop 🎉

### CODE REVIEW

**Comment by ejwyman64** [comment]
I haven't figured out how to modify the appearance of the sliders yet, I will keep working on that as well. I hope you like what I have done! Your js is great, I thought such a cool website needs an equally cool theme.

**Comment by dvontrec** [comment]
First of all, thank you.  You're Awesome!  Secondly, I like it, but I made a footer today and its causing a conflict.  I will figure that out and then merge them.

**Comment by ejwyman64** [comment]
It probably has something to do with the fact that I removed the bottom
padding on ". container" so that the white border would look right. Let's
me know if I can help out :)

**Comment by dvontrec** [comment]
I have made a production branch so that we can test this more.  I will get it added when I fix the footer.

**Pull request merged**
